### ISSUE TITLE
[BUG] 🐛  Incompatible with `injectable_generator`

### ISSUE THREAD

**Issue by moha-b** [isar/isar#1625]
### Steps to Reproduce

When I tried to add the `injectable` package to my project, I encountered an issue with `pub get`.

```shall
Because isar_generator 3.1.0 depends on analyzer >=4.6.0 <6.0.0 and injectable_generator >=2.5.0 depends on analyzer ^6.4.1, isar_generator 3.1.0 is incompatible with injectable_generator >=2.5.0.
So, because noctuary depends on both injectable_generator ^2.6.1 and isar_generator 3.1.0, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on injectable_generator: flutter pub add dev:injectable_generator:^2.4.2
```

Downgrading the injectable solved the issue, but I thought you guys might be interested in that.
### Code sample

```yaml
dependencies:
  flutter:
    sdk: flutter
  ...
  injectable: ^2.4.2
  get_it: ^7.7.0
  isar: *isar_version
  isar_flutter_libs: *isar_version
  path_provider: ^2.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  injectable_generator: ^2.6.1  # <--
  isar_generator: *isar_version  # <--
  build_runner: ^2.4.10
```

### Details

 - Flutter version: [3.22.1]
 - Isar version: [3.1.0]

---

 - [ x ] I searched for similar issues already
 - [ x ] I filled the details section with the exact device model and version
 - [ x ] I am able to provide a reproducible example

**Comment by VARWA** [comment]
I have this error too

**Comment by escamoteur** [comment]
you could try adding a dependency override for analyzer ^6.4.1 and see it it works.

**Comment by moha-b** [comment]
i just need more time to try your solution please don't close the issue

**Comment by moha-b** [comment]
```yaml
isar_version: &isar_version 3.1.0

dependencies:
  flutter:
    sdk: flutter

  gap: ^3.0.1
  flutter_staggered_grid_view: ^0.7.0
  cupertino_icons: ^1.0.8
  iconic: ^0.1.0
  # add injectable to your dependencies
  injectable: ^2.4.2
  # add get_it
  get_it: ^7.7.0
  isar: *isar_version
  isar_flutter_libs: *isar_version
  path_provider: ^2.1.3
  analyzer: ^6.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  injectable_generator: ^2.6.1
  isar_generator: *isar_version
  build_runner: ^2.4.11
```
still the same thing
```shall
Because isar_generator 3.1.0 depends on analyzer >=4.6.0 <6.0.0 and noctuary depends on analyzer ^6.4.1, isar_generator 3.1.0 is forbidden.
So, because noctuary depends on isar_generator 3.1.0, version solving failed.
```

**Comment by zraki-kenpachi** [comment]
Is this not solved yet?

**Comment by talhadengiz** [comment]
I got the same error. I am able to proceed when I use the versions as below.
```
dependencies:
  get_it: ^7.7.0
  injectable: ^2.4.4
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  injectable_generator: ^2.4.2
  isar_generator: ^3.1.0+1
  freezed: ^2.5.2
```

Incompatibility with the other package versions you are using might occur again. In my case, I had to set the freezed version to 2.5.2 instead of 2.5.7.

**Comment by zraki-kenpachi** [comment]
I can pub get now with this versions

```yaml
isar_version: &isar_version 3.1.0+1

dependencies:
  isar: *isar_version
  isar_flutter_libs: *isar_version

dev_dependencies:
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  injectable_generator: ^2.4.2
  isar_generator: *isar_version
```

may the issue have been solved but I guess not since others facing the same issue with the analyzer which appears if u try to upgrade the `injectable_generator` to `^2.5.2` look here #1564

**Comment by moha-b** [comment]
There are conflicts with Flutter version 3.27.0. I tried your solution @zraki-kenpachi , and it worked fine; however, the issue persists and may occur with other packages with different versions.
