### ISSUE TITLE
sortById() / sortByIdDesc() throw Unhandled Exception (Unknown property "id")

### ISSUE THREAD

**Issue by appano1** [isar/isar#280]
**Steps to Reproduce**
sortById() and sortByIdDesc() throw Unhandled Exception: Unknown property "id"
I think Isar generator doesn't generate id in CollectionSchema.propertyIds

**Code sample**
```dart
await isar.writeTxn((isar) {
  return isar.someObjs.putAll([someObj1, someObj2, someObj3]);
});

// These throw Unhandled Exception
await isar.someObjs.where().sortById().findAll();
await isar.someObjs.where().sortByIdDesc().findAll();
```

**Error details**
```
Unhandled Exception: Unknown property "id"
#0      buildNativeQuery (package:isar/src/native/query_build.dart:54:7)
#1      IsarCollectionImpl.buildQuery (package:isar/src/native/isar_collection_impl.dart:501:12)
#2      QueryBuilder.buildInternal (package:isar/src/query_builder.dart:252:24)
#3      QueryExecute.build (package:isar/src/query_builder_extensions.dart:101:23)
#4      QueryExecute.findAll (package:isar/src/query_builder_extensions.dart:110:32)
#5      runIsarApp (package:test_app/app/isar_app.dart:29:45)
<asynchronous suspension>
```

**Version**
 - Platform: iOS
 - Flutter version: 2.10.2
 - Isar version: 2.2.1
 - Isar Generator version: 2.2.1

**Comment by rizzi37** [comment]
check your model, if the manual id, needs to use @Id() or null makes it an auto-increment.

**Comment by ozayr** [comment]
> **Steps to Reproduce** sortById() and sortByIdDesc() throw Unhandled Exception: Unknown property "id" I think Isar generator doesn't generate id in CollectionSchema.propertyIds
> 
> **Code sample**
> 
> ```dart
> await isar.writeTxn((isar) {
>   return isar.someObjs.putAll([someObj1, someObj2, someObj3]);
> });
> 
> // These throw Unhandled Exception
> await isar.someObjs.where().sortById().findAll();
> await isar.someObjs.where().sortByIdDesc().findAll();
> ```
> 
> **Error details**
> 
> ```
> Unhandled Exception: Unknown property "id"
> #0      buildNativeQuery (package:isar/src/native/query_build.dart:54:7)
> #1      IsarCollectionImpl.buildQuery (package:isar/src/native/isar_collection_impl.dart:501:12)
> #2      QueryBuilder.buildInternal (package:isar/src/query_builder.dart:252:24)
> #3      QueryExecute.build (package:isar/src/query_builder_extensions.dart:101:23)
> #4      QueryExecute.findAll (package:isar/src/query_builder_extensions.dart:110:32)
> #5      runIsarApp (package:test_app/app/isar_app.dart:29:45)
> <asynchronous suspension>
> ```
> 
> **Version**
> 
> * Platform: iOS
> * Flutter version: 2.10.2
> * Isar version: 2.2.1
> * Isar Generator version: 2.2.1

Having the same issue, on 
`await isar.someObjs.where().anyIndexField.idProperty().findAll();`

same versions and platform as above

**Comment by rizzi37** [comment]
show your model code plz

**Comment by ozayr** [comment]
> show your model code plz

`
@freezed
@Collection()
class PatientFile with _$PatientFile {
  
  const factory PatientFile({
   int? id,
    required String idNumber,
    required String name,
    required String surname,
  }) = _PatientFile;

  factory PatientFile.fromJson(Map<String, dynamic> json) =>
      _$PatientFileFromJson(json);

}

`

**Comment by ozayr** [comment]
> show your model code plz

`@freezed
@Collection()
class PatientFile with _$PatientFile {
  
  const factory PatientFile({
   int? id,
    required String idNumber,
    required String name,
    required String surname,
  }) = _PatientFile;

  factory PatientFile.fromJson(Map<String, dynamic> json) =>
      _$PatientFileFromJson(json);

}`

**Comment by ozayr** [comment]
```
@freezed
@Collection()
class PatientFile with _$PatientFile {
  
  const factory PatientFile({
   int? id,
    required String idNumber,
    required String name,
    required String surname,
  }) = _PatientFile;

  factory PatientFile.fromJson(Map<String, dynamic> json) =>
      _$PatientFileFromJson(json);

}
```

**Comment by appano1** [comment]
> check your model, if the manual id, needs to use @id() or null makes it an auto-increment.

I tested many version of my models
When I use `.where(sort: any)`, I can use normally.

I can solve the error by adding property to the generated file.

**before**
```dart
// generated code
...
propertyIds: {'hashCode': 0, 'stringify': 1, 'text': 2},
```

**after**
```dart
// generated code
...
propertyIds: {'id': 0, 'hashCode': 1, 'stringify': 2, 'text': 3},
```

**Comment by MrDave05** [comment]
Is this issue being resolved? using `.where(sort: any)` does nothing, adding the id to `propertyIds` does nothing also.

Version

- Platform: Windows
- Flutter version: Flutter (Channel master, 2.11.0-0.0.pre.798, on Microsoft Windows [Version 10.0.19043.1586], locale en-GB)
- Isar version: 2.2.1
- Isar Generator version: 2.2.1

**Comment by ozayr** [comment]
Got around this by creating a new field in model and copying the id to it if I find the id field of the model to be null. I can then sort and query by it and set it as an index

**Comment by ozayr** [comment]
Got around this by creating a new field in model and copying the id to it if I find the id field of the model to be null. I can then sort and query by it and set it as an index

**Comment by leisim** [comment]
Fixed in latest release 👍

**Comment by debuggerx01** [comment]
@leisim Sorry but I still have same issue after upgrade to v2.4.0.
`person.dart`:
```dart
import 'package:isar/isar.dart';

part 'person.g.dart';

@Collection()
class Person {
  int id = Isar.autoIncrement;
  @Index(unique: true)
  String? name;
}
```

`main.dart`:
```dart
import 'dart:convert';

import 'package:isar/isar.dart';
import 'package:file/local.dart';
import 'package:isar_test/models/person.dart';

void main(List<String> arguments) async {
  var fs = LocalFileSystem();
  Isar.initializeLibraries(libraries: {'linux': fs.file('libisar.so').absolute.path});
  var isar = Isar.openSync(schemas: [PersonSchema], directory: fs.directory('db').path);
  await isar.writeTxn((isar) => isar.persons.putAll([
        Person()..name = 'Tom',
        Person()..name = 'Jack',
      ], replaceOnConflict: true));
  print(json.encode(await isar.persons.where().exportJson()));
  var res = await isar.persons.filter().idGreaterThan(1).exportJson();
  print(json.encode(res));
}
```
Outputs:
```shell
[{"id":1,"name":"Tom"},{"id":2,"name":"Jack"}]
Unhandled exception:
IsarError: Unknown propery "id"
#0      CollectionSchema.propertyIdOrErr (package:isar/src/collection_schema.dart:123:7)
#1      _buildCondition (package:isar/src/native/query_build.dart:225:33)
#2      _buildFilter (package:isar/src/native/query_build.dart:153:12)
#3      buildNativeQuery (package:isar/src/native/query_build.dart:44:25)
#4      IsarCollectionImpl.buildQuery (package:isar/src/native/isar_collection_impl.dart:480:12)
#5      QueryBuilder.buildInternal (package:isar/src/query_builder.dart:252:24)
#6      QueryExecute.build (package:isar/src/query_builder_extensions.dart:101:23)
#7      QueryExecute.exportJson (package:isar/src/query_builder_extensions.dart:145:54)
#8      main (file:///home/debuggerx/PycharmProjects/isar_test/main.dart:16:58)
<asynchronous suspension>
```

**Comment by SimonPeter1909** [comment]
I'm getting the same error too:
It was working fine last week.. but suddenly I'm getting this error...

This is my collection:
```
@Collection()
class RawMaterial {
  @Id()
  int? id;

  @Index(unique: true)
  late String rawMaterialCode;

  @Index(unique: true)
  late String rawMaterialName;

  late double grams;
}
```

Query:
```
static Future<RawMaterial?> getRawMaterialById({required int id}) async {
    Get.log("raw material id - $id");
    return await getIt<StorageProvider>()
        .isar
        .rawMaterials
        .where()
        .filter()
        .idEqualTo(id)
        .findFirst();
  }
```
I'm using a future builder and I'm getting the error `IsarError: Unknown propery "id"`

**Comment by leisim** [comment]
I already fixed it. New release today or tomorrow  🙂

**Comment by MeneDev** [comment]
I still have this issue in 2.5.0.

```dart
@Collection()
class LogbookEntity {
  final IsarLink<FolderEntity> folder = IsarLink<FolderEntity>();
  @Id()
  int? id;
  @Index()
  late int number;
  @Index()
  late String name;

  LogbookEntity({
    this.id,
    required this.number,
    required this.name,
  });

  LogbookEntity copyWith({
    LogbookEntityId? id,
    int? number,
    String? name,
  }) {
    return LogbookEntity(
      id: id ?? this.id,
      number: number ?? this.number,
      name: name ?? this.name,
    );
  }
}
```

in the `.g.dart`

```dart
  schema:
      '{"name":"LogbookEntity","idName":"id","properties":[{"name":"name","type":"String"},{"name":"number","type":"Long"}],"indexes":[{"name":"name","unique":false,"properties":[{"name":"name","type":"Hash","caseSensitive":true}]},{"name":"number","unique":false,"properties":[{"name":"number","type":"Value","caseSensitive":false}]}],"links":[{"name":"folder","target":"FolderEntity"}]}',
  idName: 'id',
  propertyIds: {'name': 0, 'number': 1},
  listProperties: {},
  indexIds: {'name': 0, 'number': 1},
```

as soon as I use `sortById()` (or e.g. `sortByName().thenById()`) I get `Unknown propery "id"`. Also note the missing `t` in property.

**Comment by itsJoKr** [comment]
Have the same issue.

The issue is definitelly that `id` is treated special, not as ordinary property. But then fetching fails because `Unknown propery "id"`, where id is expected to appear as ordinary property.

If I go into generated file these are giving me red flags where issue could be:

```
  schema:
      '{"name":"JournalEntry","idName":"id","properties":[{"name":"daySinceEpoch","type":"Long"},{"name":"note","type":"String"}],"indexes":[],"links":[]}',
  idName: 'id',
  propertyIds: {'daySinceEpoch': 0, 'note': 1},
```
