### ISSUE TITLE
On web : cannot read properties of undefined (reading 'idName')

### ISSUE THREAD

**Issue by FMotalleb** [isar/isar#385]
I use a method to clear my database it works fine on Linux on both (release/debug) builds but on web version (both release/debug) builds it throws an exception (browser: Google Chrome) : 
```Console
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'idName')
    at getId (collection.ts:67:30)
    at Array.map (<anonymous>)
    at query.ts:211:32
```
Full log :
**[trace.log](https://github.com/isar/isar/files/8702599/trace.log)**

Maybe my code causes this error.

The method :
```Dart
Future<void> deleteAllItems() async {
    await _isar.writeTxn(
      (isar) async {
        await isar.isarFormFields.buildQuery().deleteAll();
      },
    );
    await _isar.writeTxn(
      (isar) async {
        await isar.isarFormModels.buildQuery().deleteAll();
      },
    );
  }
```

Field Model :
```Dart
@Collection()
class IsarFormField extends FormFieldModel with EquatableMixin {
  @override
  @FieldTypeConverter()
  FieldType type;
  IsarFormField({
    required super.id,
    super.key = '',
    required super.index,
    this.type = FieldType.int,
    super.label = '',
    super.hint = '',
    super.error = '',
    super.isValid = '',
  });
}
```
Form Model :
```Dart
@Collection()
class IsarFormModel extends FormModel {
  IsarLinks<IsarFormField> isarFields = IsarLinks<IsarFormField>();
  IsarFormModel({
    required super.id,
    required super.index,
    super.title = '',
    super.description = '',
    Set<IsarFormField> fields = const {},
  }) {
    isarFields.addAll(fields);
  }
}
```

**Comment by FMotalleb** [comment]
Sorry I forgot to mention the versions
Tested on Isar both **^2.5.0** and **^3.0.0-dev.0**

**Comment by FMotalleb** [comment]
Flutter debug log output (on Isar ^3.0.0):
```
TypeError: Cannot read properties of undefined (reading 'idName')
    at getId (https://unpkg.com/isar@2.5.0/dist/index.js:1:6644)
    at Array.map (<anonymous>)
    at https://unpkg.com/isar@2.5.0/dist/index.js:1:25878
```
[link to https://unpkg.com/isar@2.5.0/dist/index.js](https://unpkg.com/isar@2.5.0/dist/index.js)

**Comment by FMotalleb** [comment]
[This](https://github.com/FMotalleb/form_generator) is the repo if you want to reproduce the error

**Comment by FMotalleb** [comment]
I've added a branch name independent for you to test I use a local package in main branch

**Comment by leisim** [comment]
Fixed in `3.0.0-dev.2`

**Comment by FMotalleb** [comment]
still facing the issue with 
```Dart
isar.xModel.buildQuery(
          whereClauses: [
            IdWhereClause.equalTo(value: input.id),
          ],
    ).deleteAll()
```
`deleteFirst()` works fine

* there is only one item with that id in DB
