### ISSUE TITLE
dlopen failed: cannot locate symbol "__gnu_Unwind_Find_exidx" on 32 bit Android 6

### ISSUE THREAD

**Issue by abs0** [isar/isar#392]
**Steps to Reproduce**
Run isar using app on 32bit Android 6.x device

This is similar to  #367 but not the same.

Since #367 was fixed isar runs fine for us on some but not all Android 32 bit devices
- Works: 64 bit Android 7, 8, 9, 10, 11 & 12
- Works: 32 bit Android 9
- Fails: 32 bit Android 6

Unfortunately we do not have any 64 bit Android 5 or 6 devices, or 32 bit Android 7 or 8 to try to narrow further). 

We're in the process of migrating from ejdb2 to isar, and this will be our first isar release

App is built with minSdkVersion 21 (Android 5.0)

Error is:
```
IsarError: Could not initialize IsarCore library for processor architecture "android_arm". If you create a Flutter app, make sure to add isar_flutter_libs to your dependencies. Invalid argument(s): Failed to load dynamic library 'libisar.so': dlopen failed: cannot locate symbol "__gnu_Unwind_Find_exidx" referenced by "/data/app/com.trainasone-1/split_config.armeabi_v7a.apk"...
**Code sample**
```

**Version**
 - Platform: Android
 - Flutter version: 3.0.1
 - Isar version: 3.0.0-dev.0
 - Isar Generator version: 3.0.0-dev.0

Device A - Moto G (2nd gen)

- board: MSM8226
- bootloader: 0x4822
- brand: motorola
- device: thea
- display: MPBS24.65-34-5
- fingerprint: motorola/thea_retgb/thea:6.0/MPBS24.65-34-5/6:user/release-keys
- hardware: qcom
- host: ilclbld106
- isPhysicalDevice: true
- manufacturer: motorola
- model: XT1072
- product: thea_retgb
- tags: release-keys
- type: user
- versionBaseOs: motorola/thea_retgb/thea:6.0/MPB24.65-34/28:user/release-keys
- versionCodename: REL
- versionIncremental: 6
- versionPreviewSdk: 0
- versionRelease: 6.0
- versionSdk: 23
- versionSecurityPatch: 2016-08-01

Device B - Yotophone2

- board: MSM8974
- bootloader: unknown
- brand: YotaPhone
- device: yotaphone2
- display: MMB29M.6.0.1-RU1.1.47
- fingerprint: YotaPhone/yotaphone2/yotaphone2:6.0.1/MMB29M/6.0.1-RU1.1.47:user/release-keys
- hardware: qcom
- host: [gerrit.yotadevices.com](http://gerrit.yotadevices.com/)
- isPhysicalDevice: true
- manufacturer: Yota Devices Limited
- model: YD201
- product: yotaphone2
- tags: release-keys
- type: user
- versionBaseOs:
- versionCodename: REL
- versionIncremental: 6.0.1-RU1.1.47
- versionPreviewSdk: 0
- versionRelease: 6.0.1
- versionSdk: 23
- versionSecurityPatch: 2017-02-05

**Comment by leisim** [comment]
Thanks for the report, I'll check it. Unfortunately I only have access to older android phones via browserstack

**Comment by leisim** [comment]
@abs0 thanks a lot but that won't be necessary. I'll oder one next week 🙂

**Comment by yaronwalterheylife** [comment]
Any update?
We are also experiencing this bug and its critical bug

**Comment by yaronwalterheylife** [comment]
isar: 2.5.0
flutter 3.0.0 channel stable
Device: [T-Mobile REVVL 4] - Android version: Android 10 (SDK 29)
Device: [Samsung Galaxy Tab A] - Android version: Android 11 (SDK 30)
Device: [Samsung Galaxy A11] - Android version: Android 10 (SDK 29)
Device: [Motorola moto g pure] - Android version: Android 11 (SDK 30)
Device: [Cloud (TruConnect) Stratus_C5_Elite] - Android version: Android 11 (SDK 30)
Device: [Google Mediatek MT8173 Chromebook] - Android version: Android 9 (SDK 28)

**Comment by leisim** [comment]
@yaronwalterheylife could you please try the newest dev version on pub.dev?

**Comment by leisim** [comment]
Good news: I found the underlying issue. The build of Isar Core used an incorrect linker. All future version of Isar will support every Android phone >= 5.0

**Comment by leisim** [comment]
Fixed for good in the newest release.

**Comment by JulienDev** [comment]
@leisim Still happening on my Nexus 5 (Android 6.0.1) using latest version available: 3.0.0-dev.12

> E/flutter (13098): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: IsarError: Could not initialize IsarCore library for processor architecture "android_arm". If you create a Flutter app, make sure to add isar_flutter_libs to your dependencies.
> E/flutter (13098): Invalid argument(s): Failed to load dynamic library 'libisar.so': dlopen failed: library "libisar.so" not found

**Comment by leisim** [comment]
@JulienDev You have a different issue:  `library "libisar.so" not `. Did you add `isar_flutter_libs`?

**Comment by JulienDev** [comment]
Yes I added it, it's working well on all other devices I've tested BTW. How can I help you resolving the issue? :)

**Comment by leisim** [comment]
Could you maybe rename your built app for example app.apk to app.zip, unzip it and check the lib folder for an libisar.so for armv7 is there?

What device do you see this issue on?

**Comment by JulienDev** [comment]
Lib folder contains armeabi-v7a, x86, x86_64, arm64-v8a
The issue is on a Nexus 5 (Android 6.0.1)

**Comment by leisim** [comment]
Thanks! I can get a Nexus 5. I'll try to reproduce it.

**Comment by JulienDev** [comment]
Awesome ! Don't hesitate to ask me anything :)

**Comment by Mayb3Nots** [comment]
Hi @leisim I got a similar error as @JulienDev 
```

IsarError: Could not initialize IsarCore library. If you create a Flutter app, make sure to add isar_flutter_libs to your dependencies: Invalid argument(s): Failed to load dynamic library 'libisar.so': dlopen failed: cannot locate symbol "__emutls_get_address" referenced by "/data/app/com.smapzone.smap-QkSMT0QOohAngLKewpq37g==/split_config.armeabi_v7a.apk!/lib/armeabi-v7a/libisar.so"...
```
However I am using version 2.5.0. Just wanting to let you know it was on a Samsung J5 Prime
