### ISSUE TITLE
Links problem

### ISSUE THREAD

**Issue by Viper-Bit** [isar/isar#466]
**Steps to Reproduce**
i get error on loading stock->section->warehouse (stock.section.value!.warehouse.loadSync();) with error:
`IsarError: IllegalArg: Link target collection does not match query collection.`

but if i uncomment Backlink and IsarLinks in Section isar works as expected

**Collections:**
```dart
@Collection()
class Warehouse {
  int? id;

  final sections = IsarLinks<Section>();

  late String name;
}

@Collection()
class Section {
  int? id;

  @Backlink(to: 'sections')
  final warehouse = IsarLink<Warehouse>();

  final stocks = IsarLinks<Stock>();

  //@Backlink(to: 'section')
  //final dummies = IsarLinks<Anything>();

  late String name;
}

@Collection()
class Product {
  int? id;

  final stocks = IsarLinks<Stock>();

  final dummies = IsarLinks<Anything>();

  late String name;
}

@Collection()
class Stock {
  int? id;

  @Backlink(to: 'stocks')
  final section = IsarLink<Section>();

  @Backlink(to: 'stocks')
  final product = IsarLink<Product>();

  late String name;
}

@Collection()
class Anything {
  int? id;

  final product = IsarLink<Product>();

  final section = IsarLink<Section>();
}
```

**Code:**
```dart
  var w = Warehouse()..name = 'warehouse 1';

  await isar.writeTxn(() async => await isar.warehouses.put(w));

  var s = Section()..name = 'section 1'..warehouse.value = w;

  await isar.writeTxn(() async {
    await isar.sections.put(s);
    await s.warehouse.save();
  });

  var p = Product()..name = 'product 1';

  await isar.writeTxn(() async => await isar.products.put(p));

  var st1 = Stock()..name = 'stock 1'..product.value = p..section.value = s;
  var st2 = Stock()..name = 'stock 2'..product.value = p..section.value = s;

  await isar.writeTxn(() async {
    await isar.stocks.putAll([st1, st2]);
    await st1.product.save();
    await st1.section.save();
    await st2.product.save();
    await st2.section.save();
  });

  var qp = await isar.products.where().findFirst();
  await qp!.stocks.load();
  for (var stock in qp.stocks.toList()) {
    stock.section.loadSync();
    stock.section.value!.warehouse.loadSync();
    print('warehouse name : ${stock.section.value!.warehouse.value!.name}');
  }
```

**Version**
 - Platform: Windows
 - Flutter version: 3.1.0-9.0.pre
 - Isar version: 3.0.0-dev.5
 - Isar Generator version: 3.0.0-dev.5

**Comment by jon-dez** [comment]
I've encountered the same error in my use case. A solution I have found was to have a backlink explicitly declared in cases where it would be implicitly created. Check out my tests in the gist below, the class of concern in my case is class `A`. I think in your case you may need to define a backlink from `Product` to `Anything` or vice versa.
https://gist.github.com/jon-dez/ba2cfcd034f12dee9fd1e7a79ebc22e6#file-isar_behavior_test-dart-L6-L29

**Comment by jon-dez** [comment]
I suspect there may be an issue with how Isar handle implicit backlinks, although I am not too sure.

**Comment by leisim** [comment]
Fixed in `3.0.0-dev.8`

**Comment by Viper-Bit** [comment]
still throws bellow exception in 3.0.0-dev.8 :
`IsarError: IllegalArg: Link target collection does not match query collection.`

**Comment by leisim** [comment]
Would you mind retrying with `3.0.0-dev.9`?

**Comment by leisim** [comment]
Fixed in 3.0.0

**Comment by arashghazi** [comment]
I use the Isar database for the android project but when I want to build that project in web type I got this error " Error: The integer literal 2020827702347742935 can't be represented exactly in JavaScript."
so, I changed the collection's Id By hand and now I have this error "IsarError (IsarError: IllegalArg: Collection id is invalid..)".
what can I do?
