### ISSUE TITLE
IsarError: Object Instance of 'Product' has no id and can therefore not be linked.

### ISSUE THREAD

**Issue by CripyIce** [isar/isar#484]
**Steps to Reproduce**
I saw a ticket with the same issue as mine just got solved and closed, but I couldn't make it work in my case.
I have two model `ShoppingList` and `Product`, and I try to add a product to a specific shopping list and get an error.

**Code sample**
`shopping_list.dart`
```dart
import 'package:isar/isar.dart';

import 'product.dart';

part 'shopping_list.g.dart';

@Collection()
class ShoppingList {
  int id = Isar.autoIncrement;
  late String name;
  late DateTime dateAdded;
  final products = IsarLinks<Product>();

  ShoppingList(this.name, this.dateAdded);
}
```

`product.dart`
```dart
import 'package:isar/isar.dart';

part 'product.g.dart';

@Collection()
class Product {
  int id = Isar.autoIncrement;
  late String? itemCode;
  late String? itemType;
  late String? itemName;
  late String? manufacturerName;
  late String? manufactureCountry;
  late String? manufacturerItemDescription;
  late String? unitQty;
  late String? quantity;
  late String? unitOfMeasure;
  late bool? bIsWeighted;
  late String? qtyInPackage;
  late double? itemPrice;
  late double? unitOfMeasurePrice;
  late bool? allowDiscount;
  late String? itemStatus;
  late String? itemId;
  int cartQuantity = 1;

  Product(
      this.itemCode,
      this.itemType,
      this.itemName,
      this.manufacturerName,
      this.manufactureCountry,
      this.manufacturerItemDescription,
      this.unitQty,
      this.quantity,
      this.unitOfMeasure,
      this.bIsWeighted,
      this.qtyInPackage,
      this.itemPrice,
      this.unitOfMeasurePrice,
      this.allowDiscount,
      this.itemStatus,
      this.itemId,
      this.cartQuantity);

  Product.fromJson(dynamic json) {
    itemCode = json['itemCode'];
    itemType = json['itemType'];
    itemName = json['itemName'];
    manufacturerName = json['manufacturerName'];
    manufactureCountry = json['manufactureCountry'];
    manufacturerItemDescription = json['manufacturerItemDescription'];
    unitQty = json['unitQty'];
    quantity = json['quantity'];
    unitOfMeasure = json['unitOfMeasure'];
    bIsWeighted = json['bIsWeighted'];
    qtyInPackage = json['qtyInPackage'];
    itemPrice = double.tryParse(json['itemPrice'].toString());
    unitOfMeasurePrice = double.tryParse(json['unitOfMeasurePrice'].toString());
    allowDiscount = json['allowDiscount'];
    itemStatus = json['itemStatus'];
    itemId = json['itemId'];
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['itemCode'] = itemCode;
    map['itemType'] = itemType;
    map['itemName'] = itemName;
    map['manufacturerName'] = manufacturerName;
    map['manufactureCountry'] = manufactureCountry;
    map['manufacturerItemDescription'] = manufacturerItemDescription;
    map['unitQty'] = unitQty;
    map['quantity'] = quantity;
    map['unitOfMeasure'] = unitOfMeasure;
    map['bIsWeighted'] = bIsWeighted;
    map['qtyInPackage'] = qtyInPackage;
    map['itemPrice'] = itemPrice;
    map['unitOfMeasurePrice'] = unitOfMeasurePrice;
    map['allowDiscount'] = allowDiscount;
    map['itemStatus'] = itemStatus;
    map['itemId'] = itemId;
    return map;
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Product &&
          runtimeType == other.runtimeType &&
          itemCode == other.itemCode;

  @override
  int get hashCode => itemCode.hashCode;
}
```

`main.dart`
```dart
  void addProductToShoppingList(int shoppingListId, Product product) async {
    final shoppingList = await _isar.shoppingLists.get(shoppingListId);
    await shoppingList!.products.load();

    shoppingList.products.add(product);

    await _isar.writeTxn(() async {
      await _isar.shoppingLists.put(shoppingList);
      await shoppingList.products.save();
    });
  }
```

**Version**
 - Platform: iOS
 - Flutter version: 3.0.4
 - Isar version: 3.0.0-dev.5
 - Isar Generator version: 3.0.0-dev.5

**Comment by leisim** [comment]
When you store a `Product`, isar needs to be able to assign an id. Otherwise it won't know what to link to. You can also assign the id yourself.

**Comment by CripyIce** [comment]
Thanks @leisim, but how can I do that?
Doesn’t `int id = Isar.autoIncrement;` take care of that?

**Comment by saropa** [comment]
I think you need the  @Id() decoration. E.g. 

  @Id()
  int id = Isar.autoIncrement;

**Comment by canastro** [comment]
@CripyIce since you're using 3.x shouldn't it be:`Id id = Isar.autoIncrement;`?

**Comment by leisim** [comment]
Fixed in `3.0.0-dev.8`

**Comment by CripyIce** [comment]
Actually it's still not fixed, for some reason `putSync` was the only fix for me.
I used the following code:
```dart
Future addProductToShoppingList(int shoppingListId, Product product) async {
  final shoppingList = await _isar.shoppingLists.get(shoppingListId);
  if (shoppingList == null) return;

  await shoppingList.products.load();
  shoppingList.products.add(product);

  _isar.writeTxnSync(() {
    _isar.shoppingLists.putSync(shoppingList);
  });
}
```

**Comment by sbenmeddour** [comment]
I'm using dev-8 build, but all getId generated methods looks like

```
int? _isarProfileGetId(IsarProfile object) {
  if (object.id == Isar.autoIncrement) {
    return null;
  } else {
    return object.id;
  }
}
```

**Comment by leisim** [comment]
@sbenmeddour that's correct. What problem are you facing?

**Comment by sbenmeddour** [comment]
I thought it is possible to add items in `IsarLinks()` with Isar.autoIncrement as id and then call `put()` with the object containig the `IsarLinks`, but I didn't understand how it works like you.

**Comment by leisim** [comment]
Yeah that's possible. Having an it set to `null` or `Isar.autoIncrement` is exactly the same and both will assign an auto increment id.

**Comment by pasblin** [comment]
Same here,

When i save a invoice  amounts links with id null , i get this error:

"Instance of 'AmountModel'" has no id and can therefore not be linked. Make sure to .put() objects before you use them in links.

`
await isar.writeTxn(() async {
      final databaseModel = await find(invoice.id!);
      await databaseModel?.amounts.reset();
      await isar.invoiceModels.put(invoice);
      await invoice.amounts.save();
});
`

**Comment by leisim** [comment]
Does your invoice have a final id field? If yes, you manually need to assign the id returned by `put()` because Isar cannot change your object.

**Comment by pasblin** [comment]
No , this is the code:

  @Collection()
  class AmountModel {
    Id? id;
    late String monthName;
    late double amount;
    late int monthNumber;
  }


  @Collection()
  class InvoiceModel {
    Id? id;
  
    late String title;
    late double amount;
    final amounts = IsarLinks<AmountModel>();
    late DateTime dateStart;
    late String rrule;
  }

**Comment by leisim** [comment]
Which version of Isar are you using?

**Comment by pasblin** [comment]
Last versión

**Comment by leisim** [comment]
@pasblin I think something went wrong with your reply

**Comment by pasblin** [comment]
Sorry i was answer you from mobile :).

I use this versions: 

  isar: ^3.0.0-dev.13
  isar_flutter_libs: ^3.0.0-dev.13
  isar_generator: ^3.0.0-dev.13

**Comment by pasblin** [comment]
When you say i need to .put() the amount model too before you can link it., 
you mean I should change the order and do this?

    await isar.writeTxn(() async {

      final databaseModel = await find(invoice.id!);

      await databaseModel?.amounts.reset();
      
      await invoice.amounts.save();

      await isar.invoiceModels.put(invoice);

   });

**Comment by pasblin** [comment]
I forgot to say that in previous versions The code works fine.

Regards
